lib: [
  "_build/install/default/lib/docaml/META" {"META"}
  "_build/install/default/lib/docaml/dune-package" {"dune-package"}
  "_build/install/default/lib/docaml/opam" {"opam"}
]
bin: [
  "_build/install/default/bin/docaml" {"docaml"}
]
share: [
  "_build/install/default/share/docaml/doc.css" {"doc.css"}
  "_build/install/default/share/docaml/doc.js" {"doc.js"}
  "_build/install/default/share/docaml/highlight.pack.js" {"highlight.pack.js"}
  "_build/install/default/share/docaml/monokai.css" {"monokai.css"}
]
doc: [
  "_build/install/default/doc/docaml/LICENSE"
  "_build/install/default/doc/docaml/README.md"
]
